name: semantic-release

on: [push]

jobs:
  semantic-release:
    
    runs-on: ubuntu-latest

    container:
      image: node:16.15-alpine

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: apk add git && npm ci && apk add zip

    - name: Launch semantic for service
      run: cd modules/service && for moduleName in service logging-index; do cd ../${moduleName} && npx semantic-release -e semantic-release-monorepo; done;
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: ZIP build
      run: cd modules/ && for moduleName in service logging-index; do zip -r ${moduleName}.zip ${moduleName}; mv ${moduleName}.zip ${moduleName}/docs/; ls -al ${moduleName}/docs/; done;



